---
version: 2
updates:
    - package-ecosystem: github-actions
      schedule:
          day: monday
          interval: monthly
          time: "05:33"
      target-branch: main
      groups:
          github-actions:
              applies-to: version-updates
              dependency-type: production
