---
name: Build docs
on:
    workflow_call:

jobs:
    build-docs:
        name: Docs build
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:

            - uses: actions/checkout@v5

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: '3.10'

            - name: Install docs deps
              run: |
                  python -m pip install --upgrade pip
                  pip install -U setuptools wheel
                  pip install .[docs]

            - name: Build docs
              run: |
                  sphinx-apidoc -o docs/source/apidoc datatractor_beam
                  sphinx-build -b html docs/source/ public/main

            - name: Upload docs artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  path: public/main
