---
name: Deploy docs
on:
    workflow_call:
    workflow_dispatch:

jobs:
    deploy-pages:
        name: Deploy docs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'

            - uses: actions/deploy-pages@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
