---
name: Deploy docs
on:
    workflow_call:
    workflow_dispatch:

jobs:
    deploy-pages:
        name: Deploy docs
        runs-on: ubuntu-latest

        permissions:
          pages: write      # to deploy to Pages
          id-token: write   # to verify the deployment originates from an appropriate source

        steps:
            - uses: actions/checkout@v5

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: '3.10'

            - uses: actions/deploy-pages@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
